// Mocks generated by Mockito 5.4.6 from annotations
// in investtrack/test/investments_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bloc/bloc.dart' as _i7;
import 'package:investtrack/application_services/blocs/authentication/bloc/authentication_bloc.dart'
    as _i3;
import 'package:investtrack/domain_services/exchange_rate_repository.dart'
    as _i6;
import 'package:investtrack/domain_services/investments_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/models.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInvestments_0 extends _i1.SmartFake implements _i2.Investments {
  _FakeInvestments_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvestment_1 extends _i1.SmartFake implements _i2.Investment {
  _FakeInvestment_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageResponse_2 extends _i1.SmartFake
    implements _i2.MessageResponse {
  _FakeMessageResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthenticationState_3 extends _i1.SmartFake
    implements _i3.AuthenticationState {
  _FakeAuthenticationState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InvestmentsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvestmentsRepository extends _i1.Mock
    implements _i4.InvestmentsRepository {
  MockInvestmentsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Investments> getInvestments({
    required String? userId,
    int? page = 1,
    int? investmentsPerPage = 6,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestments, [], {
              #userId: userId,
              #page: page,
              #investmentsPerPage: investmentsPerPage,
            }),
            returnValue: _i5.Future<_i2.Investments>.value(
              _FakeInvestments_0(
                this,
                Invocation.method(#getInvestments, [], {
                  #userId: userId,
                  #page: page,
                  #investmentsPerPage: investmentsPerPage,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Investments>);

  @override
  _i5.Future<_i2.Investment> create(_i2.Investment? investment) =>
      (super.noSuchMethod(
            Invocation.method(#create, [investment]),
            returnValue: _i5.Future<_i2.Investment>.value(
              _FakeInvestment_1(this, Invocation.method(#create, [investment])),
            ),
          )
          as _i5.Future<_i2.Investment>);

  @override
  _i5.Future<_i2.Investment> update(_i2.Investment? investment) =>
      (super.noSuchMethod(
            Invocation.method(#update, [investment]),
            returnValue: _i5.Future<_i2.Investment>.value(
              _FakeInvestment_1(this, Invocation.method(#update, [investment])),
            ),
          )
          as _i5.Future<_i2.Investment>);

  @override
  _i5.Future<_i2.MessageResponse> delete(_i2.Investment? investment) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [investment]),
            returnValue: _i5.Future<_i2.MessageResponse>.value(
              _FakeMessageResponse_2(
                this,
                Invocation.method(#delete, [investment]),
              ),
            ),
          )
          as _i5.Future<_i2.MessageResponse>);

  @override
  _i5.Future<double> fetchPriceChange(String? ticker) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPriceChange, [ticker]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<double> fetchChangePercentage(String? ticker) =>
      (super.noSuchMethod(
            Invocation.method(#fetchChangePercentage, [ticker]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);
}

/// A class which mocks [ExchangeRateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeRateRepository extends _i1.Mock
    implements _i6.ExchangeRateRepository {
  MockExchangeRateRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<double> getExchangeRate({
    required String? fromCurrency,
    String? toCurrency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExchangeRate, [], {
              #fromCurrency: fromCurrency,
              #toCurrency: toCurrency,
            }),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);
}

/// A class which mocks [AuthenticationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationBloc extends _i1.Mock
    implements _i3.AuthenticationBloc {
  MockAuthenticationBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthenticationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthenticationState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AuthenticationState);

  @override
  _i5.Stream<_i3.AuthenticationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.AuthenticationState>.empty(),
          )
          as _i5.Stream<_i3.AuthenticationState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.AuthenticationEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.AuthenticationEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AuthenticationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.AuthenticationEvent>(
    _i7.EventHandler<E, _i3.AuthenticationState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i3.AuthenticationEvent, _i3.AuthenticationState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i3.AuthenticationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onChange(_i7.Change<_i3.AuthenticationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
