name: user_repository
description: Dart package which manages the user domain.
publish_to: none
version: 1.0.0
repository: https://github.com/Turskyi/flutter_life_coaching_ai

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  models:
    path: ../../models
  shared_preferences: ^2.5.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
