name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none
version: 1.0.0
repository: https://github.com/Turskyi/flutter_life_coaching_ai

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  clerk_auth: ^0.0.10-beta
  envied: ^1.2.0
  models:
    path: ../../models
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: any
  envied_generator: ^1.2.0
  lints: ^6.0.0
  test: ^1.26.3
